BOARD_TAG					=	ATtiny84
ARDUINO_PORT			= /dev/ttyUSB0
ARDUINO_LIBS			= LiquidCrystal Adafruit_NeoPixel
ISP_PORT					= /dev/ttyUSB0
ISP_PROG					= -c stk500v1
ARDUINO_VAR_PATH	= ~/sketchbook/hardware/attiny/
include /usr/share/arduino/Arduino.mk
